export const regionOptions = [
  "af-south-1",
  "ap-east-1",
  "ap-northeast-1",
  "ap-northeast-2",
  "ap-northeast-3",
  "ap-south-1",
  "ap-south-2",
  "ap-southeast-1",
  "ap-southeast-2",
  "ap-southeast-3",
  "ap-southeast-4",
  "ap-southeast-5",
  "ca-central-1",
  "eu-central-1",
  "eu-central-2",
  "eu-north-1",
];

export const instanceOptions = [
    "t2.nano",
    "m7a.12xLarge",
  "m7a.16xLarge",
  "c5.large",
  "c5.xlarge",
  "c5.2xlarge",
  "c5.4xlarge",
  "c5.9xlarge",
  "c5.12xlarge",
  "c5.18xlarge",
  "c5.24xlarge",
  "c5.metal",
  "c5a.large",
  "c5a.xlarge",
  "c5a.2xlarge",
  "c5a.4xlarge",
  "c5a.8xlarge",
  "c5a.12xlarge",
  "c5a.16xlarge",
  "c5a.24xlarge",
  "c5ad.large",
  "c5ad.xlarge",
];

export const pricingModelOptions = ["ondemand", "reserved"];
