import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  response: {
    portfolioName: "Test00Demo16",
    type: "m7a.12xLarge",
    region: "af-south-1",
    instanceType: "a9caea33-6afd-461d-a1df-7c095a247454",
    uuid: "UUID/Instance Name",
    pricingModel: "ondemand",
    maxCpuUtilization: 100,
    maxMemoryUsed: 100,
    maxNetworkBandwidth: 100,
    maxDiskBandwidth: 100,
    maxIOPS: 100,
  },
  formData: {
    portfolioName: "",
    region: "",
    instanceType: "",
    uuid: "",
    pricingModel: "",
    maxCpuUtilization: 0,
    maxMemoryUsed: 0,
    maxNetworkBandwidth: 0,
    maxDiskBandwidth: 0,
    maxIOPS: 0,
  },
  instanceStats: [
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247451",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247452",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247452",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247454",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a24745",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247456",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247457",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247458",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247451",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247452",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247452",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247454",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a24745",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247456",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247457",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
    {
      portfolioName: "Test00Demo16",
      type: "m7a.12xLarge",
      region: "af-south-1",
      instanceType: "a9caea33-6afd-461d-a1df-7c095a247458",
      uuid: "UUID/Instance Name",
      pricingModel: "ondemand",
      maxCpuUtilization: 100,
      maxMemoryUsed: 100,
      maxNetworkBandwidth: 100,
      maxDiskBandwidth: 100,
      maxIOPS: 100,
    },
  ],
};

const instanceSlice = createSlice({
  name: "instance",
  initialState,
  reducers: {
    addInstance(state, action) {
      const newInstance = {
        id: state.instanceStats.length + 1,
        ...action.payload,
      };
      state.instanceStats.push(newInstance);
    },
    updateFormData(state, action) {
      state.formData = { ...state.formData, ...action.payload };
    },
    updateInstance(state, action) {
      const index = state.instanceStats.findIndex(
        (instance) => instance.id === action.payload.id
      );
      if (index !== -1) {
        state.instanceStats[index] = {
          ...state.instanceStats[index],
          ...action.payload,
        };
      }
    },
  },
});

export const { addInstance, updateInstance, updateFormData } =
  instanceSlice.actions;

export default instanceSlice.reducer;
